# The easiest way to access MongoDB from 
# another server is to use an SSH tunnel.
# Otherwise, remove the "127.0.0.1:" and
# open ports 27017 and 8081 on the firewall.
version: "3.1"
services:

  stormy_mongodb:
    build: d-mongodb
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - "/opt/mongodb:/data"

  stormy_mongoexpress:
    image: mongo-express
    restart: always
    ports:
      - "127.0.0.1:8081:8081"
    links:
      - stormy_mongodb:mongo
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=REPLACEME

